kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
  - role: worker
  - role: worker


# starting a container useing docker
# docker run -d -p 3000:8080 nginx

# start a pod using kubectl
# kubectl run nginx --image=nginx --port=80

# check the status of the pod 
# kubectl get pod

# check the logs 
# kubectl logs nginx

# port forward 
# kubectl port-forward nginx 8080:80

# starting a nginx containe inside a pod in k8 cluster
# kubectl run nginx --image=nginx --port=80

# get the image name 
# kubectl get pod nginx -o=jsonpath='{.spec.containers[0].image}'

# to fetch all the detail of a pod 
# kubectl describe nginx 

# to delete a pod 
# kubectl delete pod nginx 


# if any pod get cresh it will not delete that it will retry or restert it after a time gap 
 

#  what we have learnt till now

# cluster -  it is a group of node that are connected to each other 

# node  - it is a machine that is connected to the cluster and that is used to run the pods 

# pod - it is the smallest unit of kubernetes and it is used to run the containers 

# container - it is a  package of code and its dependency  which is used to run the application 

# image - it is a template of a container which is used to create the containers 

#-----------------------------------------

# deployement - it is used to deploy the application 
# replicaset - it is used to create the multiple replica of the application 
# services - it is used to expose the application 
# ingress - it is used to expose the application to the outside world 
# configmap - it is used to store the configuration data 
# secret - it is used to store the sensitive data 
# volume - it is used to store the data 
# persistent volume - it is used to store the data 
# persistent volume claim - it is used to store the data 