kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
  - role: worker
  - role: worker


# starting a container useing docker
# docker run -d -p 3000:8080 nginx

# start a pod using kubectl
# kubectl run nginx --image=nginx --port=80

# check the status of the pod 
# kubectl get pod

# check the logs 
# kubectl logs nginx

# port forward 
# kubectl port-forward nginx 8080:80

# starting a nginx containe inside a pod in k8 cluster
# kubectl run nginx --image=nginx --port=80

# get the image name 
# kubectl get pod nginx -o=jsonpath='{.spec.containers[0].image}'

# to fetch all the detail of a pod 
# kubectl describe nginx 

# to delete a pod 
# kubectl delete pod nginx 
